from gax.definitions import Alignment, GafRecord, MultipathAlignment


class Graph: ...

def convert_gam_to_gaf(data: list[Alignment], graph: Graph) -> list[GafRecord]: ...
def convert_gaf_to_gam(data: list[GafRecord], graph: Graph) -> list[Alignment]: ...
def convert_gam_to_gamp(data: list[Alignment]) -> list[MultipathAlignment]: ...
def convert_gamp_to_gam(data: list[MultipathAlignment]) -> list[Alignment]: ...
def load_graph(path: str) -> Graph: ...
